version: 1
description: ""
parallel: 2
properties:
  auto_dependency: true
jobs:
- "sri_flights"
- "d_airports"
- "d_planes"
- "d_carriers"
- "f_flight"
- "sri_airports"
- "sri_planes"
- "sri_carriers"
